apiVersion: v1
kind: Pod
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  containers:
    - name: hello-server
      image: retriever/hello-server:1.1
      ports:
        - name: http
          containerPort: 8080
        - name: admin
          containerPort: 8081
      resources:
        limits:
          cpu: 0.2
          memory: "100Mi"
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 8081
        initialDelaySeconds: 60
        periodSeconds: 10
      env:
        - name: HELLO_SERVER_GREETING_LIMIT
          valueFrom:
            configMapKeyRef:
              name: hello-server-config
              key: greetingLimit
        - name: HELLO_SERVER_DEFAULT_NAME
          valueFrom:
            configMapKeyRef:
              name: hello-server-config
              key: defaultName