apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-server
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: hello-server
             servicePort: 8080
