apiVersion: v1
kind: Service
metadata:
  name: "hello-server"
spec:
  type: NodePort
  selector:
    app: "hello-server"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31000