apiVersion: v1
kind: Service
metadata:
  name: "hello-server"
spec:
  type: NodePort
  selector:
    app: "hello-server"
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
    - name: admin
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31001
